/// Profile 字段预设选项
abstract final class ProfileOptions {
  /// Occupation 选项列表（与 Preference occupationTypes 对齐）
  static const List<String> occupations = [
    'Tech',
    'Finance',
    'Education',
    'Healthcare',
    'Design',
    'Legal',
    'Media',
    'Sales',
    'Management',
    'Other',
  ];

  /// 全球主要城市列表（人口≥50万，格式: "City, State, Country"，来源：GeoNames CC BY 4.0）
  static const List<String> cities = [
    'Aba, Abia State, Nigeria',
    'Abeokuta, Ogun State, Nigeria',
    'Abidjan, Abidjan Autonomous District, Ivory Coast',
    'Abobo, Abidjan Autonomous District, Ivory Coast',
    'Abu Dhabi, United Arab Emirates',
    'Abuja, FCT, Nigeria',
    'Abū Ghurayb, Baghdad, Iraq',
    'Acapulco de Juárez, Guerrero, Mexico',
    'Accra, Greater Accra, Ghana',
    'Adachi, Tokyo, Japan',
    'Adana, Turkey',
    'Addis Ababa, Ethiopia',
    'Adelaide, South Australia, Australia',
    'Aden, Yemen',
    'Agadir, Souss-Massa, Morocco',
    'Agra, Uttar Pradesh, India',
    'Aguascalientes, Mexico',
    'Ahmedabad, Gujarat, India',
    'Ahvaz, Khuzestan, Iran',
    'Aihara, Kanagawa, Japan',
    'Ajegunle, Lagos, Nigeria',
    'Ajmer, Rajasthan, India',
    'Aktobe, Kazakhstan',
    'Akure, Ondo State, Nigeria',
    'Al Ain City, Abu Dhabi, United Arab Emirates',
    'Al Aḩmadī, Al Ahmadi, Kuwait',
    'Al Başrah al Qadīmah, Basra, Iraq',
    'Al Fayyum, Faiyum, Egypt',
    'Al Mansurah, Dakahlia, Egypt',
    'Al Mawşil al Jadīdah, Nineveh, Iraq',
    'Al Maḩallah al Kubrá, Gharbia, Egypt',
    'Al Ḩudaydah, Al Hudaydah, Yemen',
    'Albuquerque, New Mexico, United States',
    'Aleppo, Syria',
    'Alexandria, Egypt',
    'Algiers, Algeria',
    'Almaty, Kazakhstan',
    'Alīgarh, Uttar Pradesh, India',
    'Amman, Jordan',
    'Amravati, Maharashtra, India',
    'Amritsar, Punjab, India',
    'Amsterdam, North Holland, The Netherlands',
    'Andijon, Andijan Region, Uzbekistan',
    'Ankang, Shaanxi, China',
    'Ankara, Turkey',
    'Anqing, Anhui, China',
    'Ansan-si, Gyeonggi-do, South Korea',
    'Anshan, Liaoning, China',
    'Anshun, Guizhou, China',
    'Antalya, Turkey',
    'Antananarivo, Analamanga, Madagascar',
    'Antipolo, Calabarzon, Philippines',
    'Antwerpen, Flanders, Belgium',
    'Anyang, Henan, China',
    'Anyang-si, Gyeonggi-do, South Korea',
    'Aparecida de Goiânia, Goias, Brazil',
    'Aqsu, Xinjiang, China',
    'Ar Raqqah, Raqqa, Syria',
    'Aracaju, Sergipe, Brazil',
    'Arequipa, Peru',
    'Arusha, Tanzania',
    'Arāk, Markazi, Iran',
    'Ashgabat, Turkmenistan',
    'Asmara, Maekel, Eritrea',
    'Assiut, Asyut, Egypt',
    'Astrakhan, Astrakhan Oblast, Russia',
    'Asunción, Asuncion, Paraguay',
    'Athens, Attica, Greece',
    'Atlanta, Georgia, United States',
    'Auckland, New Zealand',
    'Aurangabad, Maharashtra, India',
    'Austin, Texas, United States',
    'Baghdad, Iraq',
    'Bahawalpur, Punjab, Pakistan',
    'Bahçelievler, Istanbul, Turkey',
    'Baise, Guangxi, China',
    'Baku, Baki, Azerbaijan',
    'Balikpapan, East Kalimantan, Indonesia',
    'Baltimore, Maryland, United States',
    'Bamako, Mali',
    'Banan, Chongqing, China',
    'Bandar Lampung, Lampung, Indonesia',
    'Bandung, West Java, Indonesia',
    'Bangkok, Thailand',
    'Bangui, Central African Republic',
    'Banjarmasin, South Kalimantan, Indonesia',
    'Bannu, Khyber Pakhtunkhwa, Pakistan',
    'Banqiao, Taipei, Taiwan',
    'Bao\'an, Guangdong, China',
    'Baoding, Hebei, China',
    'Baoji, Shaanxi, China',
    'Baoshan, Shanghai, China',
    'Baoshan, Yunnan, China',
    'Baotou, Inner Mongolia, China',
    'Barcelona, Anzoategui, Venezuela',
    'Barcelona, Catalonia, Spain',
    'Bareilly, Uttar Pradesh, India',
    'Barnaul, Altai Krai, Russia',
    'Barquisimeto, Lara, Venezuela',
    'Barranquilla, Atlantico, Colombia',
    'Basrah, Basra, Iraq',
    'Batam, Riau, Indonesia',
    'Battagram, Khyber Pakhtunkhwa, Pakistan',
    'Bauchi, Nigeria',
    'Bayan Nur, Inner Mongolia, China',
    'Bazhong, Sichuan, China',
    'Bağcılar, Istanbul, Turkey',
    'Beihai, Guangxi, China',
    'Beijing, China',
    'Beira, Sofala, Mozambique',
    'Beirut, Lebanon',
    'Bekasi, West Java, Indonesia',
    'Belgrade, Central Serbia, Serbia',
    'Belo Horizonte, Minas Gerais, Brazil',
    'Belém, Para, Brazil',
    'Bengaluru, Karnataka, India',
    'Bengbu, Anhui, China',
    'Benghazi, Banghazi, Libya',
    'Benguela, Angola',
    'Benin City, Edo State, Nigeria',
    'Benoni, Gauteng, South Africa',
    'Benxi, Liaoning, China',
    'Berlin, State of Berlin, Germany',
    'Bhavnagar, Gujarat, India',
    'Bhayandar, Maharashtra, India',
    'Bhilai, Chhattisgarh, India',
    'Bhiwandi, Maharashtra, India',
    'Bhopal, Madhya Pradesh, India',
    'Bhubaneswar, Odisha, India',
    'Bijie, Guizhou, China',
    'Bikaner, Rajasthan, India',
    'Bilimora, Gujarat, India',
    'Binzhou, Shandong, China',
    'Birmingham, England, United Kingdom',
    'Bishkek, Kyrgyzstan',
    'Biên Hòa, Dong Nai, Vietnam',
    'Blantyre, Southern Region, Malawi',
    'Bloemfontein, Free State, South Africa',
    'Bobo-Dioulasso, Hauts-Bassins, Burkina Faso',
    'Bogor, West Java, Indonesia',
    'Bogotá, Bogota D.C., Colombia',
    'Bokāro, Jharkhand, India',
    'Borama, Awdal, Somalia',
    'Borivli, Maharashtra, India',
    'Boston, Massachusetts, United States',
    'Bouaké, Vallee du Bandama District, Ivory Coast',
    'Bozhou, Anhui, China',
    'Brampton, Ontario, Canada',
    'Brasília, Federal District, Brazil',
    'Brazzaville, Republic of the Congo',
    'Bremen, Germany',
    'Brisbane, Queensland, Australia',
    'Brooklyn, New York, United States',
    'Brussels, Brussels Capital, Belgium',
    'Bucaramanga, Santander Department, Colombia',
    'Bucharest, Romania',
    'Bucheon-si, Gyeonggi-do, South Korea',
    'Buda, Budapest, Hungary',
    'Budapest, Hungary',
    'Budta, Autonomous Region in Muslim Mindanao, Philippines',
    'Buenos Aires, Buenos Aires F.D., Argentina',
    'Bujumbura, Bujumbura Mairie, Burundi',
    'Bukavu, South Kivu, Democratic Republic of the Congo',
    'Bukit Rahman Putra, Selangor, Malaysia',
    'Bulawayo, Zimbabwe',
    'Buraydah, Al-Qassim Region, Saudi Arabia',
    'Bursa, Bursa Province, Turkey',
    'Busan, South Korea',
    'Bình Thạnh, Ho Chi Minh City (HCMC), Vietnam',
    'Cabinda, Angola',
    'Cagayan de Oro, Northern Mindanao, Philippines',
    'Cairo, Egypt',
    'Calabar, Cross River State, Nigeria',
    'Calamba, Calabarzon, Philippines',
    'Calgary, Alberta, Canada',
    'Cali, Valle del Cauca Department, Colombia',
    'Callao, Peru',
    'Caloocan, National Capital Region, Philippines',
    'Calumbo, Bengo, Angola',
    'Camama, Luanda, Angola',
    'Camayenne, Conakry, Guinea',
    'Campinas, Sao Paulo, Brazil',
    'Campo Grande, Mato Grosso do Sul, Brazil',
    'Campos dos Goytacazes, Rio de Janeiro, Brazil',
    'Cancún, Quintana Roo, Mexico',
    'Cangzhou, Hebei, China',
    'Cape Town, Western Cape, South Africa',
    'Caracas, Distrito Federal, Venezuela',
    'Carrefour, Ouest, Haiti',
    'Cartagena, Bolivar, Colombia',
    'Casablanca, Casablanca-Settat, Morocco',
    'Cebu City, Central Visayas, Philippines',
    'Chandigarh, India',
    'Changchun, Jilin, China',
    'Changde, Hunan, China',
    'Changning, Shanghai, China',
    'Changsha, Guangdong, China',
    'Changsha, Hunan, China',
    'Changshu, Jiangsu, China',
    'Changwon, Gyeongsangnam-do, South Korea',
    'Changzhi, Shanxi, China',
    'Changzhou, Jiangsu, China',
    'Chaozhou, Guangdong, China',
    'Charlotte, North Carolina, United States',
    'Chattogram, Chittagong, Bangladesh',
    'Chelyabinsk, Russia',
    'Chengdu, Sichuan, China',
    'Chennai, Tamil Nadu, India',
    'Chenzhou, Hunan, China',
    'Cheonan, Chungcheongnam-do, South Korea',
    'Cheongju-si, North Chungcheong, South Korea',
    'Chiba, Japan',
    'Chicago, Illinois, United States',
    'Chiclayo, Lambayeque, Peru',
    'Chihuahua, Mexico',
    'Chisinau, Chisinau Municipality, Moldova',
    'Chizhou, Anhui, China',
    'Chongming, China',
    'Chongqing, China',
    'Chuxiong, Yunnan, China',
    'Chuzhou, Anhui, China',
    'Chợ Lớn, Ho Chi Minh City (HCMC), Vietnam',
    'Cimahi, West Java, Indonesia',
    'Ciudad Guayana, Bolivar, Venezuela',
    'Ciudad Juárez, Chihuahua, Mexico',
    'Ciudad Nezahualcoyotl, Mexico, Mexico',
    'Cixi, Zhejiang, China',
    'Cochabamba, Bolivia',
    'Coimbatore, Tamil Nadu, India',
    'Colombo, Western Province, Sri Lanka',
    'Columbus, Ohio, United States',
    'Comilla, Chittagong, Bangladesh',
    'Conakry, Guinea',
    'Contagem, Minas Gerais, Brazil',
    'Copenhagen, Capital Region, Denmark',
    'Cotonou, Littoral, Benin',
    'Coyoacán, Mexico City, Mexico',
    'Cuauhtémoc, Mexico City, Mexico',
    'Cuautitlán Izcalli, Mexico, Mexico',
    'Cuenca, Azuay, Ecuador',
    'Cuiabá, Mato Grosso, Brazil',
    'Culiacán, Sinaloa, Mexico',
    'Curitiba, Parana, Brazil',
    'Cuttack, Odisha, India',
    'Córdoba, Cordoba, Argentina',
    'Cúcuta, Norte de Santander Department, Colombia',
    'Cần Thơ, Can Tho City, Vietnam',
    'Da Nang, Da Nang City, Vietnam',
    'Daegu, South Korea',
    'Daejeon, South Korea',
    'Dakar, Senegal',
    'Dalian, Liaoning, China',
    'Dallas, Texas, United States',
    'Damascus, Damascus Governorate, Syria',
    'Dammam, Eastern Province, Saudi Arabia',
    'Dandong, Liaoning, China',
    'Daqing, Heilongjiang, China',
    'Dar es Salaam, Dar es Salaam Region, Tanzania',
    'Datong, Shanxi, China',
    'Davao, Davao Region, Philippines',
    'Daxing’anling, Heilongjiang, China',
    'Dazhou, Sichuan, China',
    'Dehradun, Uttarakhand, India',
    'Delhi, India',
    'Denpasar, Bali, Indonesia',
    'Denver, Colorado, United States',
    'Depok, West Java, Indonesia',
    'Dera Ismail Khan, Khyber Pakhtunkhwa, Pakistan',
    'Detroit, Michigan, United States',
    'Deyang, Sichuan, China',
    'Dezhou, Shandong, China',
    'Dhaka, Dhaka Division, Bangladesh',
    'Dhanbad, Jharkhand, India',
    'Dhārāvi, Maharashtra, India',
    'Diyarbakır, Diyarbakir Province, Turkey',
    'Djibouti, Djibouti',
    'Dnipro, Dnipropetrovsk, Ukraine',
    'Dodoma, Tanzania',
    'Dombivali, Maharashtra, India',
    'Donetsk, Ukraine',
    'Dongguan, Guangdong, China',
    'Dongying, Shandong, China',
    'Dortmund, North Rhine-Westphalia, Germany',
    'Douala, Littoral, Cameroon',
    'Dresden, Saxony, Germany',
    'Dubai, United Arab Emirates',
    'Dublin, Leinster, Ireland',
    'Duisburg, North Rhine-Westphalia, Germany',
    'Duque de Caxias, Rio de Janeiro, Brazil',
    'Durban, KwaZulu-Natal, South Africa',
    'Durgapur, West Bengal, India',
    'Dushanbe, Tajikistan',
    'Düsseldorf, North Rhine-Westphalia, Germany',
    'Ebute Ikorodu, Lagos, Nigeria',
    'Ecatepec de Morelos, Mexico, Mexico',
    'Edinburgh, Scotland, United Kingdom',
    'Edmonton, Alberta, Canada',
    'Edogawe, Tokyo, Japan',
    'El Paso, Texas, United States',
    'Enugu, Enugu State, Nigeria',
    'Erbil, Iraq',
    'Erode, Tamil Nadu, India',
    'Erzurum, Turkey',
    'Esenler, Istanbul, Turkey',
    'Eskişehir, Eskisehir, Turkey',
    'Essen, North Rhine-Westphalia, Germany',
    'Evaton, Gauteng, South Africa',
    'E’zhou, Hubei, China',
    'Faisalabad, Punjab, Pakistan',
    'Faridabad, Haryana, India',
    'Feira de Santana, Bahia, Brazil',
    'Fengxiang, Shanghai, China',
    'Fes, Fes-Meknes, Morocco',
    'Florianópolis, Santa Catarina, Brazil',
    'Fort Worth, Texas, United States',
    'Fortaleza, Ceara, Brazil',
    'Foshan, Guangdong, China',
    'Frankfurt am Main, Hesse, Germany',
    'Freetown, Western Area, Sierra Leone',
    'Fresno, California, United States',
    'Fukuoka, Japan',
    'Fushun, Liaoning, China',
    'Fuxin, Liaoning, China',
    'Fuyang, Anhui, China',
    'Fuzhou, Fujian, China',
    'Fuzhou, Jiangxi, China',
    'Ganzhou, Jiangxi, China',
    'Gaziantep, Turkey',
    'Gazipur, Dhaka Division, Bangladesh',
    'General Santos, Soccsksargen, Philippines',
    'Genoa, Liguria, Italy',
    'Ghāziābād, Uttar Pradesh, India',
    'Giza, Egypt',
    'Glasgow, Scotland, United Kingdom',
    'Goiânia, Goias, Brazil',
    'Gold Coast, Queensland, Australia',
    'Golfe, Luanda, Angola',
    'Gombe, Gombe State, Nigeria',
    'Gorakhpur, Haryana, India',
    'Gorakhpur, Uttar Pradesh, India',
    'Gothenburg, Vaestra Goetaland, Sweden',
    'Goyang-si, Gyeonggi-do, South Korea',
    'Gqeberha, Eastern Cape, South Africa',
    'Guadalajara, Jalisco, Mexico',
    'Guadalupe, Nuevo Leon, Mexico',
    'Guangyuan, Sichuan, China',
    'Guangzhou, Guangdong, China',
    'Guang’an, Sichuan, China',
    'Guankou, Hunan, China',
    'Guarulhos, Sao Paulo, Brazil',
    'Guatemala City, Guatemala, Guatemala',
    'Guayaquil, Guayas, Ecuador',
    'Guigang, Guangxi, China',
    'Guilin, Guangxi, China',
    'Guiyang, Guizhou, China',
    'Gujranwala, Punjab, Pakistan',
    'Gujrat, Punjab, Pakistan',
    'Guli, Zhejiang, China',
    'Guntur, Andhra Pradesh, India',
    'Gurugram, Haryana, India',
    'Gustavo Adolfo Madero, Mexico City, Mexico',
    'Guwahati, Assam, India',
    'Gwalior, Madhya Pradesh, India',
    'Gwangju, South Korea',
    'Ha\'il, Ha\'il Region, Saudi Arabia',
    'Hachiōji, Tokyo, Japan',
    'Haikou, Hainan, China',
    'Haiphong, Hai Phong, Vietnam',
    'Hamadān, Hamadan Province, Iran',
    'Hamamatsu, Shizuoka, Japan',
    'Hamburg, Germany',
    'Hamhŭng, South Hamgyong, North Korea',
    'Hamilton, Ontario, Canada',
    'Handan, Hebei, China',
    'Hangzhou, Zhejiang, China',
    'Hannover, Lower Saxony, Germany',
    'Hanoi, Vietnam',
    'Hanzhong, Shaanxi, China',
    'Harare, Zimbabwe',
    'Harbin, Heilongjiang, China',
    'Havana, Cuba',
    'Hebi, Henan, China',
    'Hefei, Anhui, China',
    'Hegang, Heilongjiang, China',
    'Helsinki, Uusimaa, Finland',
    'Hengshui, Hebei, China',
    'Hengyang, Hunan, China',
    'Hermosillo, Sonora, Mexico',
    'Heroica Matamoros, Tamaulipas, Mexico',
    'Herāt, Herat, Afghanistan',
    'Heshan, Hunan, China',
    'Heze, Shandong, China',
    'Hezhou, Guangxi, China',
    'Himeji, Hyogo, Japan',
    'Hiroshima, Japan',
    'Hlaingthaya, Yangon, Myanmar',
    'Ho Chi Minh City, Ho Chi Minh City (HCMC), Vietnam',
    'Hohhot, Inner Mongolia, China',
    'Hoji ya Henda, Luanda, Angola',
    'Homs, Syria',
    'Homyel\', Homyel\' Voblasc\', Belarus',
    'Honchō, Chiba, Japan',
    'Hong Kong Island, Hong Kong',
    'Hong Kong, Hong Kong',
    'Hongkou, Shanghai, China',
    'Houston, Texas, United States',
    'Howrah, West Bengal, India',
    'Huai\'an, Jiangsu, China',
    'Huaibei, Anhui, China',
    'Huaihua, Hunan, China',
    'Huainan, Anhui, China',
    'Huambo, Angola',
    'Huangpu, Shanghai, China',
    'Huangshi, Hubei, China',
    'Hubballi, Karnataka, India',
    'Huizhou, Guangdong, China',
    'Huludao, Liaoning, China',
    'Huzhou, Zhejiang, China',
    'Huế, Thua Thien Hue Province, Vietnam',
    'Hwaseong-si, Gyeonggi-do, South Korea',
    'Hyderabad, Sindh, Pakistan',
    'Hyderabad, Telangana, India',
    'Ibadan, Oyo State, Nigeria',
    'Ibagué, Tolima Department, Colombia',
    'Ibb, Ibb Governorate, Yemen',
    'Ile-Ife, Osun State, Nigeria',
    'Ilorin, Kwara State, Nigeria',
    'Incheon, South Korea',
    'Indianapolis, Indiana, United States',
    'Indore, Madhya Pradesh, India',
    'Ipoh, Perak, Malaysia',
    'Irbid, Jordan',
    'Irkutsk, Irkutsk Oblast, Russia',
    'Isfahan, Iran',
    'Iskandar Puteri, Johor, Malaysia',
    'Islamabad, Pakistan',
    'Istanbul, Turkey',
    'Itabashi, Tokyo, Japan',
    'Izhevsk, Udmurtiya Republic, Russia',
    'Iztapalapa, Mexico City, Mexico',
    'Jabalpur, Madhya Pradesh, India',
    'Jaboatão dos Guararapes, Pernambuco, Brazil',
    'Jaboatão, Pernambuco, Brazil',
    'Jacksonville, Florida, United States',
    'Jaipur, Rajasthan, India',
    'Jakarta, Indonesia',
    'Jalandhar, Punjab, India',
    'Jambi City, Jambi, Indonesia',
    'Jammu, Jammu and Kashmir, India',
    'Jamnagar, Gujarat, India',
    'Jamshedpur, Jharkhand, India',
    'Jeddah, Mecca Region, Saudi Arabia',
    'Jeonju, Jeollabuk-do, South Korea',
    'Jepara, Central Java, Indonesia',
    'Jerusalem, Israel',
    'Jiading, Shanghai, China',
    'Jiamusi, Heilongjiang, China',
    'Jiangmen, Guangdong, China',
    'Jiangyin, Jiangsu, China',
    'Jiaozhou, Shandong, China',
    'Jiaozuo, Henan, China',
    'Jiaxing, Zhejiang, China',
    'Jieyang, Guangdong, China',
    'Jilin, China',
    'Jinan, Shandong, China',
    'Jingmen, Hubei, China',
    'Jingzhou, Hubei, China',
    'Jing’an, Shanghai, China',
    'Jinhua, Zhejiang, China',
    'Jining, Shandong, China',
    'Jinjiang, Fujian, China',
    'Jinshan, Shanghai, China',
    'Jinzhong, Shanxi, China',
    'Jinzhou, Liaoning, China',
    'Jiujiang, Jiangxi, China',
    'Ji’an, Jiangxi, China',
    'Jodhpur, Rajasthan, India',
    'Johannesburg, Gauteng, South Africa',
    'Johor Bahru, Johor, Malaysia',
    'Jos, Plateau State, Nigeria',
    'João Pessoa, Paraiba, Brazil',
    'Juiz de Fora, Minas Gerais, Brazil',
    'Kabul, Afghanistan',
    'Kaduna, Kaduna State, Nigeria',
    'Kagoshima, Japan',
    'Kaifeng, Henan, China',
    'Kakamega, Kakamega County, Kenya',
    'Kalaburagi, Karnataka, India',
    'Kalininskiy, St.-Petersburg, Russia',
    'Kallakurichi, Tamil Nadu, India',
    'Kalyān, Maharashtra, India',
    'Kampala, Central Region, Uganda',
    'Kampung Baru Subang, Selangor, Malaysia',
    'Kampung Larkin Lama, Johor, Malaysia',
    'Kananga, Kasai-Central, Democratic Republic of the Congo',
    'Kanayannur, Kerala, India',
    'Kandahār, Kandahar, Afghanistan',
    'Kano, Kano State, Nigeria',
    'Kanpur, Uttar Pradesh, India',
    'Kaohsiung, Takao, Taiwan',
    'Karachi, Sindh, Pakistan',
    'Karaj, Alborz Province, Iran',
    'Karbala, Iraq',
    'Karol Bāgh, Delhi, India',
    'Kashgar, Xinjiang, China',
    'Kasur, Punjab, Pakistan',
    'Kathmandu, Bagmati Province, Nepal',
    'Katsina, Katsina State, Nigeria',
    'Kawaguchi, Saitama, Japan',
    'Kawasaki, Kanagawa, Japan',
    'Kayseri, Turkey',
    'Kazan, Tatarstan Republic, Russia',
    'Kemerovo, Kuzbass, Russia',
    'Kennedy, Bogota D.C., Colombia',
    'Kerman, Iran',
    'Kermanshah, Kermanshah Province, Iran',
    'Khabarovsk Vtoroy, Khabarovsk, Russia',
    'Khabarovsk, Russia',
    'Kharkiv, Ukraine',
    'Khartoum North, Khartoum, Sudan',
    'Khartoum, Sudan',
    'Khulna, Khulna Division, Bangladesh',
    'Kigali, Rwanda',
    'Kikolo, Luanda, Angola',
    'Kikwit, Kwilu, Democratic Republic of the Congo',
    'Kimhae, Gyeongsangnam-do, South Korea',
    'Kingston, Jamaica',
    'Kinshasa, Democratic Republic of the Congo',
    'Kirkuk, Iraq',
    'Kirov, Kirov Oblast, Russia',
    'Kisangani, Tshopo, Democratic Republic of the Congo',
    'Kitakyushu, Fukuoka, Japan',
    'Kitwe, Copperbelt, Zambia',
    'Kobe, Hyogo, Japan',
    'Kochi, Kerala, India',
    'Kolhāpur, Maharashtra, India',
    'Kolkata, West Bengal, India',
    'Kolwezi, Lualaba, Democratic Republic of the Congo',
    'Konya, Turkey',
    'Korla, Xinjiang, China',
    'Kota Bharu, Kelantan, Malaysia',
    'Kota Damansara, Selangor, Malaysia',
    'Kota Kinabalu, Sabah, Malaysia',
    'Kota Kuala Muda, Kedah, Malaysia',
    'Kota, Rajasthan, India',
    'Kotō, Kumamoto, Japan',
    'Kowloon, Hong Kong',
    'Kozhikode, Kerala, India',
    'Kraków, Lesser Poland, Poland',
    'Krasnodar, Krasnodar Krai, Russia',
    'Krasnoyarsk, Krasnoyarsk Krai, Russia',
    'Kryvyy Rih, Dnipropetrovsk, Ukraine',
    'Kuala Lumpur, Malaysia',
    'Kuantan, Pahang, Malaysia',
    'Kumamoto, Japan',
    'Kumasi, Ashanti, Ghana',
    'Kunming, Yunnan, China',
    'Kunshan, Jiangsu, China',
    'Kyiv, Kyiv City, Ukraine',
    'Kyoto, Japan',
    'Köln, North Rhine-Westphalia, Germany',
    'La Paz, La Paz Department, Bolivia',
    'Lagos, Nigeria',
    'Lahore, Punjab, Pakistan',
    'Laibin, Guangxi, China',
    'Laiwu, Shandong, China',
    'Langfang, Hebei, China',
    'Lanzhou, Gansu, China',
    'Las Piñas, National Capital Region, Philippines',
    'Las Vegas, Nevada, United States',
    'Latakia, Syria',
    'Leeds, England, United Kingdom',
    'Leipzig, Saxony, Germany',
    'Leshan, Sichuan, China',
    'León de los Aldama, Guanajuato, Mexico',
    'Lianyungang, Jiangsu, China',
    'Liaocheng, Shandong, China',
    'Liaoyang, Liaoning, China',
    'Libreville, Estuaire, Gabon',
    'Likasi, Haut-Katanga, Democratic Republic of the Congo',
    'Lilongwe, Central Region, Malawi',
    'Lima, Lima Province, Peru',
    'Linfen, Shanxi, China',
    'Linyi, Shandong, China',
    'Lipetsk, Lipetsk Oblast, Russia',
    'Lisbon, Portugal',
    'Liupanshui, Guizhou, China',
    'Liuzhou, Guangxi, China',
    'Lomé, Maritime, Togo',
    'London, England, United Kingdom',
    'Londrina, Parana, Brazil',
    'Longyan, Fujian, China',
    'Loni, Uttar Pradesh, India',
    'Los Angeles, California, United States',
    'Louisville, Kentucky, United States',
    'Luancheng, Hebei, China',
    'Luanda, Angola',
    'Lubango, Huila, Angola',
    'Lubumbashi, Haut-Katanga, Democratic Republic of the Congo',
    'Lucknow, Uttar Pradesh, India',
    'Ludhiana, Punjab, India',
    'Luohe, Henan, China',
    'Luohu District, Guangdong, China',
    'Luoyang, Henan, China',
    'Lusaka, Lusaka Province, Zambia',
    'Luzhou, Sichuan, China',
    'Lu’an, Anhui, China',
    'Lviv, Ukraine',
    'Lyon, Rhone-Alpes, France',
    'Lüliang, Shanxi, China',
    'Macapá, Amapa, Brazil',
    'Macau, Macao',
    'Maceió, Alagoas, Brazil',
    'Madinah, Medina Region, Saudi Arabia',
    'Madrid, Spain',
    'Madurai, Tamil Nadu, India',
    'Madīnat an Naşr, Cairo, Egypt',
    'Maianga, Luanda, Angola',
    'Maiduguri, Borno State, Nigeria',
    'Maipú, Santiago Metropolitan, Chile',
    'Makassar, South Sulawesi, Indonesia',
    'Makati City, National Capital Region, Philippines',
    'Makhachkala, Dagestan, Russia',
    'Makkah, Mecca Region, Saudi Arabia',
    'Malacca, Melaka, Malaysia',
    'Malang, East Java, Indonesia',
    'Malatya, Turkey',
    'Malingao, Soccsksargen, Philippines',
    'Managua, Managua Department, Nicaragua',
    'Manaus, Amazonas, Brazil',
    'Manchester, England, United Kingdom',
    'Mandalay, Mandalay Region, Myanmar',
    'Manhattan, New York, United States',
    'Manila, National Capital Region, Philippines',
    'Maoming, Guangdong, China',
    'Maputo, Maputo City, Mozambique',
    'Mar del Plata, Buenos Aires, Argentina',
    'Maracaibo, Zulia, Venezuela',
    'Marrakesh, Marrakesh-Safi, Morocco',
    'Marseille, Provence-Alpes-Cote d\'Azur, France',
    'Mashhad, Razavi Khorasan, Iran',
    'Matola, Maputo Province, Mozambique',
    'Matsuyama, Ehime, Japan',
    'Maturín, Monagas, Venezuela',
    'Mazār-e Sharīf, Balkh, Afghanistan',
    'Ma’anshan, Anhui, China',
    'Mbeya, Tanzania',
    'Mbuji-Mayi, East Kasai, Democratic Republic of the Congo',
    'Medan, North Sumatra, Indonesia',
    'Medellín, Antioquia, Colombia',
    'Meerut, Uttar Pradesh, India',
    'Meishan, Sichuan, China',
    'Meizhou, Guangdong, China',
    'Meknes, Fes-Meknes, Morocco',
    'Melbourne, Victoria, Australia',
    'Memphis, Tennessee, United States',
    'Mengzi, Yunnan, China',
    'Mersin, Turkey',
    'Mexicali, Baja California, Mexico',
    'Mexico City, Mexico',
    'Mianyang, Sichuan, China',
    'Mianzhu, Deyang, Sichuan, Sichuan, China',
    'Milan, Lombardy, Italy',
    'Milwaukee, Wisconsin, United States',
    'Minhang, Shanghai, China',
    'Minsk, Minsk City, Belarus',
    'Mirpur Model Thana, Dhaka Division, Bangladesh',
    'Mississauga, Ontario, Canada',
    'Mogadishu, Banaadir, Somalia',
    'Mohammadpur, Rajshahi Division, Bangladesh',
    'Mombasa, Mombasa County, Kenya',
    'Monrovia, Montserrado County, Liberia',
    'Monterrey, Nuevo Leon, Mexico',
    'Montevideo, Montevideo Department, Uruguay',
    'Montréal, Quebec, Canada',
    'Morelia, Michoacan, Mexico',
    'Morādābād, Uttar Pradesh, India',
    'Moscow, Russia',
    'Mosul, Nineveh, Iraq',
    'Mudanjiang, Heilongjiang, China',
    'Mukalla, Muhafazat Hadramaout, Yemen',
    'Mukim Pulai, Johor, Malaysia',
    'Mulenvos, Luanda, Angola',
    'Multan, Punjab, Pakistan',
    'Mumbai, Maharashtra, India',
    'Munich, Bavaria, Germany',
    'Muntinlupa, Calabarzon, Philippines',
    'Muscat, Oman',
    'Muzaffarābād, Azad Kashmir, Pakistan',
    'Mwanza, Tanzania',
    'Mysuru, Karnataka, India',
    'Málaga, Andalusia, Spain',
    'Mérida, Yucatan, Mexico',
    'N\'Djamena, Chad',
    'Naberezhnyye Chelny, Tatarstan Republic, Russia',
    'Nagoya, Aichi, Japan',
    'Nagpur, Maharashtra, India',
    'Nairobi, Nairobi County, Kenya',
    'Najafgarh, Delhi, India',
    'Najrān, Najran Region, Saudi Arabia',
    'Nakuru, Nakuru County, Kenya',
    'Namangan, Uzbekistan',
    'Nampula, Mozambique',
    'Nanchang, Jiangxi, China',
    'Nanchong, Sichuan, China',
    'Nanded, Maharashtra, India',
    'Nanjing, Jiangsu, China',
    'Nanning, Guangxi, China',
    'Nansana, Central Region, Uganda',
    'Nantong, Jiangsu, China',
    'Nanyang, Henan, China',
    'Naples, Campania, Italy',
    'Narela, Delhi, India',
    'Nashik, Maharashtra, India',
    'Nashville, Tennessee, United States',
    'Nasiriyah, Dhi Qar, Iraq',
    'Natal, Rio Grande do Norte, Brazil',
    'Naucalpan de Juárez, Mexico, Mexico',
    'Navi Mumbai, Maharashtra, India',
    'Nay Pyi Taw, Myanmar',
    'Ndola, Copperbelt, Zambia',
    'Neijiang, Sichuan, China',
    'Nellore, Andhra Pradesh, India',
    'New Kingston, Saint Andrew Parish, Jamaica',
    'New South Memphis, Tennessee, United States',
    'New Taipei City, Taipei, Taiwan',
    'New Territories, Hong Kong',
    'New York City, New York, United States',
    'Newcastle, New South Wales, Australia',
    'Nha Trang, Khanh Hoa, Vietnam',
    'Niamey, Niger',
    'Niigata, Japan',
    'Nilüfer, Bursa Province, Turkey',
    'Ningbo, Zhejiang, China',
    'Nizhniy Novgorod, Nizhny Novgorod Oblast, Russia',
    'Nouakchott, Mauritania',
    'Nova Iguaçu, Rio de Janeiro, Brazil',
    'Novokuznetsk, Kuzbass, Russia',
    'Novosibirsk, Novosibirsk Oblast, Russia',
    'Nowrangapur, Odisha, India',
    'Nuremberg, Bavaria, Germany',
    'Nyala, Southern Darfur, Sudan',
    'Odesa, Ukraine',
    'Okara, Punjab, Pakistan',
    'Okayama, Japan',
    'Oklahoma City, Oklahoma, United States',
    'Omdurman, Khartoum, Sudan',
    'Omsk, Omsk Oblast, Russia',
    'Onitsha, Anambra, Nigeria',
    'Oran, Algeria',
    'Ordos, Inner Mongolia, China',
    'Orenburg, Orenburg Oblast, Russia',
    'Orūmīyeh, West Azerbaijan, Iran',
    'Osaka, Japan',
    'Osasco, Sao Paulo, Brazil',
    'Oslo, Norway',
    'Osogbo, Osun State, Nigeria',
    'Ottawa, Ontario, Canada',
    'Ouagadougou, Centre, Burkina Faso',
    'Oujda, Oriental, Morocco',
    'Owerri, Imo State, Nigeria',
    'Oyo, Oyo State, Nigeria',
    'Padang, West Sumatra, Indonesia',
    'Palembang, South Sumatra, Indonesia',
    'Palermo, Sicily, Italy',
    'Pallabi, Dhaka Division, Bangladesh',
    'Panjin, Liaoning, China',
    'Panshan, Liaoning, China',
    'Panzhihua, Sichuan, China',
    'Paranaque City, National Capital Region, Philippines',
    'Paris, Ile-de-France, France',
    'Pasig City, National Capital Region, Philippines',
    'Pasir Gudang, Johor, Malaysia',
    'Patna, Bihar, India',
    'Pekanbaru, Riau, Indonesia',
    'Pelentong, Johor, Malaysia',
    'Penza, Penza Oblast, Russia',
    'Perm, Perm Krai, Russia',
    'Perth, Western Australia, Australia',
    'Peshawar, Khyber Pakhtunkhwa, Pakistan',
    'Pest, Budapest, Hungary',
    'Petaling Jaya, Selangor, Malaysia',
    'Philadelphia, Pennsylvania, United States',
    'Phnom Penh, Cambodia',
    'Phoenix, Arizona, United States',
    'Pietermaritzburg, KwaZulu-Natal, South Africa',
    'Pikine, Dakar, Senegal',
    'Pimpri, Maharashtra, India',
    'Pimpri-Chinchwad, Maharashtra, India',
    'Pingdingshan, Henan, China',
    'Pingdu, Shandong, China',
    'Pingliang, Gansu, China',
    'Pingxiang, Jiangxi, China',
    'Pointe-Noire, Republic of the Congo',
    'Pokhara, Gandaki Pradesh, Nepal',
    'Pontianak, West Kalimantan, Indonesia',
    'Port Harcourt, Rivers State, Nigeria',
    'Port Said, Egypt',
    'Port-au-Prince, Ouest, Haiti',
    'Portland, Oregon, United States',
    'Porto Alegre, Rio Grande do Sul, Brazil',
    'Porto Velho, Rondonia, Brazil',
    'Poznań, Greater Poland, Poland',
    'Prague, Czechia',
    'Prayagraj, Uttar Pradesh, India',
    'Pretoria, Gauteng, South Africa',
    'Pristina, Kosovo',
    'Pudong, Shanghai, China',
    'Puducherry, India',
    'Puebla, Mexico',
    'Puente Alto, Santiago Metropolitan, Chile',
    'Pune, Maharashtra, India',
    'Puning, Guangdong, China',
    'Putian, Fujian, China',
    'Putuo, Shanghai, China',
    'Puyang, Henan, China',
    'Puyang, Zhejiang, China',
    'Pyongyang, North Korea',
    'Qingdao, Shandong, China',
    'Qingpu, Shanghai, China',
    'Qingyang, Gansu, China',
    'Qingyuan, Guangdong, China',
    'Qinhuangdao, Hebei, China',
    'Qinzhou, Guangxi, China',
    'Qionghai, Hainan, China',
    'Qiqihar, Heilongjiang, China',
    'Qom, Qom Province, Iran',
    'Quanzhou, Fujian, China',
    'Queens, New York, United States',
    'Quetta, Balochistan, Pakistan',
    'Quezon City, National Capital Region, Philippines',
    'Qui Nhon, Gia Lai, Vietnam',
    'Quito, Pichincha, Ecuador',
    'Qujing, Yunnan, China',
    'Quzhou, Zhejiang, China',
    'Québec, Quebec, Canada',
    'Rabat, Rabat-Sale-Kenitra, Morocco',
    'Rahim Yar Khan, Punjab, Pakistan',
    'Raipur, Chhattisgarh, India',
    'Rajshahi, Rajshahi Division, Bangladesh',
    'Ranchi, Jharkhand, India',
    'Rangpur, Rangpur Division, Bangladesh',
    'Rasapūdipalem, Andhra Pradesh, India',
    'Rasht, Gilan Province, Iran',
    'Rawalpindi, Punjab, Pakistan',
    'Ra’s Bayrūt, Beirut, Lebanon',
    'Recife, Pernambuco, Brazil',
    'Reynosa, Tamaulipas, Mexico',
    'Ribeirão Preto, Sao Paulo, Brazil',
    'Riga, Latvia',
    'Rio de Janeiro, Brazil',
    'Riyadh, Riyadh Region, Saudi Arabia',
    'Rizhao, Shandong, China',
    'Rohini, Delhi, India',
    'Rome, Lazio, Italy',
    'Rosario, Santa Fe, Argentina',
    'Rostov-on-Don, Rostov, Russia',
    'Rotterdam, South Holland, The Netherlands',
    'Rui’an, Zhejiang, China',
    'Ryazan’, Ryazan Oblast, Russia',
    'Rājkot, Gujarat, India',
    'Sacramento, California, United States',
    'Sadr City, Baghdad, Iraq',
    'Sagamihara, Kanagawa, Japan',
    'Sahiwal, Punjab, Pakistan',
    'Saint Petersburg, St.-Petersburg, Russia',
    'Saitama, Japan',
    'Sakai, Osaka, Japan',
    'Salem, Tamil Nadu, India',
    'Salta, Argentina',
    'Saltillo, Coahuila, Mexico',
    'Salvador, Bahia, Brazil',
    'Salé, Rabat-Sale-Kenitra, Morocco',
    'Samara, Samara Oblast, Russia',
    'Samarinda, East Kalimantan, Indonesia',
    'Samarkand, Samarqand Region, Uzbekistan',
    'San Antonio, Texas, United States',
    'San Diego, California, United States',
    'San Francisco, California, United States',
    'San Jose, California, United States',
    'San Luis Potosí, San Luis Potosi, Mexico',
    'San Miguel de Tucumán, Tucuman, Argentina',
    'San Pedro Sula, Cortes Department, Honduras',
    'San Salvador, San Salvador Department, El Salvador',
    'Sanaa, Amanat Alasimah, Yemen',
    'Sanhe, Hebei, China',
    'Sanmenxia, Henan, China',
    'Sanming, Fujian, China',
    'Santa Cruz de la Sierra, Santa Cruz Department, Bolivia',
    'Santiago de Cuba, Santiago de Cuba Province, Cuba',
    'Santiago de Querétaro, Queretaro, Mexico',
    'Santiago de los Caballeros, Santiago Province, Dominican Republic',
    'Santiago, Santiago Metropolitan, Chile',
    'Santo André, Sao Paulo, Brazil',
    'Santo Domingo Este, Santo Domingo Province, Dominican Republic',
    'Santo Domingo Oeste, Santo Domingo Province, Dominican Republic',
    'Santo Domingo, Nacional, Dominican Republic',
    'Sanya, Hainan, China',
    'Sapporo, Hokkaido, Japan',
    'Sarajevo, Federation of B&H, Bosnia and Herzegovina',
    'Saratov, Saratov Oblast, Russia',
    'Sargodha, Punjab, Pakistan',
    'Seattle, Washington, United States',
    'Selayang Baru Utara, Selangor, Malaysia',
    'Semarang, Central Java, Indonesia',
    'Sendai, Miyagi, Japan',
    'Seongnam-si, Gyeonggi-do, South Korea',
    'Seoul, South Korea',
    'Serang, Banten, Indonesia',
    'Serra, Espirito Santo, Brazil',
    'Setagaya, Tokyo, Japan',
    'Sevastopol, Sevastopol City, Ukraine',
    'Sevilla, Andalusia, Spain',
    'Shah Alam, Selangor, Malaysia',
    'Shanghai, China',
    'Shangluo, Shaanxi, China',
    'Shangqiu, Henan, China',
    'Shangrao, Jiangxi, China',
    'Shangyu, Zhejiang, China',
    'Shantou, Guangdong, China',
    'Shaoguan, Guangdong, China',
    'Shaoxing, Zhejiang, China',
    'Shaoyang, Hunan, China',
    'Sharjah, United Arab Emirates',
    'Sheffield, England, United Kingdom',
    'Shekhupura, Punjab, Pakistan',
    'Shenyang, Liaoning, China',
    'Shenzhen, Guangdong, China',
    'Shihezi, Xinjiang, China',
    'Shijiazhuang, Hebei, China',
    'Shiraz, Fars, Iran',
    'Shivaji Nagar, Maharashtra, India',
    'Shiyan, Hubei, China',
    'Shizuishan, Ningxia, China',
    'Shizuoka, Japan',
    'Sholapur, Maharashtra, India',
    'Shuangyashan, Heilongjiang, China',
    'Shubrā al Khaymah, Qalyubia, Egypt',
    'Shymkent, Kazakhstan',
    'Sialkot, Punjab, Pakistan',
    'Siliguri, West Bengal, India',
    'Singapore, Singapore',
    'Siping, Jilin, China',
    'Situbondo, East Java, Indonesia',
    'Soacha, Cundinamarca, Colombia',
    'Sofia, Sofia-Capital, Bulgaria',
    'Sokoto, Nigeria',
    'Songjiang, Shanghai, China',
    'Sorocaba, Sao Paulo, Brazil',
    'Soshanguve, Gauteng, South Africa',
    'South Boston, Massachusetts, United States',
    'South Tangerang, Banten, Indonesia',
    'Soweto, Gauteng, South Africa',
    'Srinagar, Jammu and Kashmir, India',
    'Stockholm, Sweden',
    'Stuttgart, Baden-Wurttemberg, Germany',
    'Subang Jaya, Selangor, Malaysia',
    'Suez, Egypt',
    'Suginami, Ibaraki, Japan',
    'Suining, Sichuan, China',
    'Suizhou, Hubei, China',
    'Sukkur, Sindh, Pakistan',
    'Sulaymaniyah, Iraq',
    'Sulţānah, Medina Region, Saudi Arabia',
    'Sungai Petani, Kedah, Malaysia',
    'Suqian, Jiangsu, China',
    'Surabaya, East Java, Indonesia',
    'Surakarta, Central Java, Indonesia',
    'Surat, Gujarat, India',
    'Surrey, British Columbia, Canada',
    'Suwon, Gyeonggi-do, South Korea',
    'Suzhou, Anhui, China',
    'Suzhou, Jiangsu, China',
    'Sydney, New South Wales, Australia',
    'São Bernardo do Campo, Sao Paulo, Brazil',
    'São José dos Campos, Sao Paulo, Brazil',
    'São Luís, Maranhao, Brazil',
    'São Paulo, Sao Paulo, Brazil',
    'Sāngli, Maharashtra, India',
    'Tabriz, East Azerbaijan, Iran',
    'Tabuk, Tabuk Region, Saudi Arabia',
    'Taguig, National Capital Region, Philippines',
    'Taicang, Jiangsu, China',
    'Taichung, Taiwan, Taiwan',
    'Tainan, Taiwan, Taiwan',
    'Taipei, Taiwan, Taiwan',
    'Taiyuan, Shanxi, China',
    'Taiz, Ta\'izz, Yemen',
    'Taizhou, Jiangsu, China',
    'Taizhou, Zhejiang, China',
    'Tai’an, Shandong, China',
    'Takeo, Cambodia',
    'Talatona, Luanda, Angola',
    'Tangerang, Banten, Indonesia',
    'Tanggu, Tianjin, China',
    'Tangier, Tanger-Tetouan-Al Hoceima, Morocco',
    'Tangshan, Hebei, China',
    'Tanta, Gharbia, Egypt',
    'Tashkent, Uzbekistan',
    'Tasikmalaya, West Java, Indonesia',
    'Ta’if, Mecca Region, Saudi Arabia',
    'Tbilisi, Georgia',
    'Tegucigalpa, Francisco Morazan Department, Honduras',
    'Tehran, Iran',
    'Teni, Tamil Nadu, India',
    'Teresina, Piaui, Brazil',
    'Thanh Hóa, Thanh Hoa Province, Vietnam',
    'The Bronx, New York, United States',
    'Thembisa, Gauteng, South Africa',
    'Thiruvananthapuram, Kerala, India',
    'Thuận An, Ho Chi Minh City (HCMC), Vietnam',
    'Thāne, Maharashtra, India',
    'Thủ Đức, Ho Chi Minh City (HCMC), Vietnam',
    'Tianjin, China',
    'Tianshui, Gansu, China',
    'Tijuana, Baja California, Mexico',
    'Tiruchirappalli, Tamil Nadu, India',
    'Tirunelveli, Tamil Nadu, India',
    'Tiruppur, Tamil Nadu, India',
    'Tlalnepantla, Mexico, Mexico',
    'Tlalpan, Mexico City, Mexico',
    'Tlaquepaque, Jalisco, Mexico',
    'Tokyo, Japan',
    'Tolyatti, Samara Oblast, Russia',
    'Tomsk, Tomsk Oblast, Russia',
    'Tonghua, Jilin, China',
    'Toronto, Ontario, Canada',
    'Torreón, Coahuila, Mexico',
    'Touba, Diourbel Region, Senegal',
    'Toulouse, Occitanie, France',
    'Tripoli, Libya',
    'Trujillo, La Libertad, Peru',
    'Tshikapa, Kasai, Democratic Republic of the Congo',
    'Tucson, Arizona, United States',
    'Tuen Mun, Hong Kong',
    'Tunis, Tunis Governorate, Tunisia',
    'Turin, Piedmont, Italy',
    'Tuxtla, Chiapas, Mexico',
    'Tyumen, Tyumen Oblast, Russia',
    'Uberlândia, Minas Gerais, Brazil',
    'Ufa, Bashkortostan Republic, Russia',
    'Ujjain, Madhya Pradesh, India',
    'Ulan Bator, Ulaanbaatar, Mongolia',
    'Ulanqab, Inner Mongolia, China',
    'Ulhasnagar, Maharashtra, India',
    'Ulsan, South Korea',
    'Ulyanovsk, Russia',
    'Umraniye, Istanbul, Turkey',
    'Utsunomiya, Tochigi, Japan',
    'Vadodara, Gujarat, India',
    'Valencia, Carabobo, Venezuela',
    'Valencia, Spain',
    'Valenzuela, National Capital Region, Philippines',
    'Van, Turkey',
    'Vancouver, British Columbia, Canada',
    'Varanasi, Uttar Pradesh, India',
    'Viana, Luanda, Angola',
    'Victoria de Durango, Durango, Mexico',
    'Victoria, Central and Western, Hong Kong',
    'Vienna, State of Vienna, Austria',
    'Vientiane, Vientiane Prefecture, Laos',
    'Vijayawada, Andhra Pradesh, India',
    'Villa Nueva, Guatemala, Guatemala',
    'Vilnius, Lithuania',
    'Vinh, Nghe An Province, Vietnam',
    'Virār, Maharashtra, India',
    'Visakhapatnam, Andhra Pradesh, India',
    'Vladivostok, Primorye, Russia',
    'Volgograd, Volgograd Oblast, Russia',
    'Voronezh, Voronezh Oblast, Russia',
    'Wanning, Hainan, China',
    'Wanxian, Chongqing, China',
    'Wanzhou, Chongqing, China',
    'Warangal, Telangana, India',
    'Warri, Delta, Nigeria',
    'Warsaw, Mazovia, Poland',
    'Washington, District of Columbia, United States',
    'Weifang, Shandong, China',
    'Weihai, Shandong, China',
    'Weinan, Shaanxi, China',
    'Wenchang, Hainan, China',
    'Wenzhou, Zhejiang, China',
    'Winnipeg, Manitoba, Canada',
    'Wrocław, Lower Silesia, Poland',
    'Wuhan, Hubei, China',
    'Wuhu, Anhui, China',
    'Wuwei, Gansu, China',
    'Wuxi, Jiangsu, China',
    'Wuzhong, Ningxia, China',
    'Wuzhou, Guangxi, China',
    'Xiamen, Fujian, China',
    'Xiangtan, Hunan, China',
    'Xiangyang, Hubei, China',
    'Xianning, Hubei, China',
    'Xianyang, Shaanxi, China',
    'Xiaogan, Hubei, China',
    'Xingtai, Hebei, China',
    'Xining, Qinghai, China',
    'Xinxiang, Henan, China',
    'Xinyang, Henan, China',
    'Xinyu, Jiangxi, China',
    'Xinzhou, Shanxi, China',
    'Xi’an, Shaanxi, China',
    'Xuancheng, Anhui, China',
    'Xuchang, Henan, China',
    'Xuhui, Shanghai, China',
    'Xuzhou, Jiangsu, China',
    'Ya\'an, Sichuan, China',
    'Yancheng, Jiangsu, China',
    'Yangjiang, Guangdong, China',
    'Yangon, Myanmar',
    'Yangpu, Shanghai, China',
    'Yangquan, Shanxi, China',
    'Yangzhou, Jiangsu, China',
    'Yantai, Shandong, China',
    'Yaoundé, Centre, Cameroon',
    'Yaroslavl, Yaroslavl Oblast, Russia',
    'Yekaterinburg, Sverdlovsk Oblast, Russia',
    'Yerevan, Armenia',
    'Yibin, Sichuan, China',
    'Yichang, Hubei, China',
    'Yichun, Jiangxi, China',
    'Yinchuan, Ningxia, China',
    'Yingkou, Liaoning, China',
    'Yiwu, Zhejiang, China',
    'Yixing, Jiangsu, China',
    'Yokohama, Kanagawa, Japan',
    'Yongzhou, Hunan, China',
    'Yueyang, Hunan, China',
    'Yulin, Guangxi, China',
    'Yuncheng, Shanxi, China',
    'Yunfu, Guangdong, China',
    'Zagreb, Croatia',
    'Zahedan, Sistan and Baluchestan, Iran',
    'Zamboanga, Zamboanga Peninsula, Philippines',
    'Zanzibar, Zanzibar Urban/West, Tanzania',
    'Zaozhuang, Shandong, China',
    'Zapopan, Jalisco, Mexico',
    'Zaporizhzhya, Zaporizhzhia, Ukraine',
    'Zaragoza, Aragon, Spain',
    'Zaria, Kaduna State, Nigeria',
    'Zarqa, Jordan',
    'Zhabei, Shanghai, China',
    'Zhangjiagang, Jiangsu, China',
    'Zhangjiakou, Hebei, China',
    'Zhangye, Gansu, China',
    'Zhangzhou, Fujian, China',
    'Zhanjiang, Guangdong, China',
    'Zhaoqing, Guangdong, China',
    'Zhaotong, Yunnan, China',
    'Zhengzhou, Henan, China',
    'Zhenjiang, Jiangsu, China',
    'Zhongshan, Guangdong, China',
    'Zhongwei, Ningxia, China',
    'Zhoukou, Henan, China',
    'Zhoushan, Zhejiang, China',
    'Zhu Cheng City, Shandong, China',
    'Zhuhai, Guangdong, China',
    'Zhumadian, Henan, China',
    'Zhuzhou, Hunan, China',
    'Zibo, Shandong, China',
    'Zigong, Sichuan, China',
    'Ziyang, Sichuan, China',
    'Zunyi, Guizhou, China',
    'Álvaro Obregón, Mexico City, Mexico',
    'Çankaya, Ankara, Turkey',
    'Ürümqi, Xinjiang, China',
    'Üsküdar, Istanbul, Turkey',
    'Āsansol, West Bengal, India',
    'Āzādshahr, Hamadan Province, Iran',
    'İzmir, Izmir Province, Turkey',
    'Łódź, Lodz Voivodeship, Poland',
    'Ōta, Tokyo, Japan',
  ];
}
